<?php

namespace examples\exampleBundle\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SecurityUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecurityUserRepository extends EntityRepository
{
}