<?php

namespace examples\exampleBundle\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SecurityRolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecurityRolRepository extends EntityRepository
{
}